#考虑其他插件取消本事件，如果事件被其他插件取消，则不会执行。
#格子序号，鼠标点击指定格子序号时，物品栏外面 -999 不限制填"-"
#需要左键，必须鼠标左键点击才会触发
#需要右键，必须鼠标右键点击才会触发
#需要shift，必须shift键点击才会触发
#鼠标物品，被光标所拿起来的物品，空气 AIR 不限制填"-"
#点击物品，鼠标点击的物品。空气 AIR 不限制填"-"

#点击时玩家命令，点击界面外面后玩家执行的命令 不执行填"-"
#点击时后台命令，点击界面外面后后台执行的命令 不执行填"-"
点击命令:
  - 考虑其他插件取消本事件: true
    格子序号: -999
    需要左键: false
    需要右键: false
    需要shift: false
    鼠标物品: "AIR"
    点击物品: "AIR"
    Action类型: "-"
    Click类型: "-"
    物品栏种类: "-"
    点击时玩家命令: "-"
    点击时后台命令: "-"